### ISSUE TITLE
 'Resource file not found' when unpacking with Tilengine Python bindings

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/ResourcePacker#1]
Hi,

I purchased the ResourcePacker from itch.io, and it seems to successfully work at packing my assets without an AES key. I'm having a problem unpacking them using the Tilengine Python binding.

Here is a simple Python script that attempts to unpack a resource and create a spriteset from an asset:
```python
# test.py
import os

os.add_dll_directory(os.getcwd())

from tilengine import *

engine = Engine.create(480, 270, 1, 1, 1)
engine.set_log_level(LogLevel.VERBOSE)
engine.open_resource_pack('assets.dat')

Spriteset.fromfile("test_asset")
```
I had to make some modifications to the binding to fix string encoding, as shown in this PR https://github.com/megamarc/PyTilengine/pull/5

It results in the following output
```
PS C:\Users\flyho\workspace\resourcepacker-test> python .\test.py
Tilengine v2.9.1 64-bit built Apr  1 2021 08:10:58
Tilengine: Resource file not found
Traceback (most recent call last):
  File "C:\Users\flyho\workspace\resourcepacker-test\test.py", line 11, in <module>
    Spriteset.fromfile("test_asset")
  File "C:\Users\flyho\workspace\resourcepacker-test\tilengine.py", line 930, in fromfile
    _raise_exception()
  File "C:\Users\flyho\workspace\resourcepacker-test\tilengine.py", line 364, in _raise_exception
    raise TilengineException(error_string.decode())
tilengine.TilengineException: 'Resource file not found'
```
Here is my folder structure:
```
C:\USERS\FLYHO\WORKSPACE\RESOURCEPACKER-TEST
│   assets.dat
│   librespack.a
│   SDL2.dll
│   test.py
│   Tilengine.dll
│   tilengine.py
│
└───include
        ResPack.h
```
Is there anything I'm missing or doing incorrectly?

**Comment by megamarc** [comment]
Hi Daniel!Thanks for your purchase and support 😀Let me check this issue. Recently I updated ResourcePacker but not the loader inside Tilengine. I'm quite sure they're incompatible right now, I have to update it. Let me fix it in the next hours and I'll tell you when i'ts done.Sorry for the inconvenience 😶El 9 sept. 2021 18:43, Daniel Holmes ***@***.***> escribió:

Hi,

I purchased the ResourcePacker from itch.io, and it seems to successfully work at packing my assets without an AES key. I'm having a problem unpacking them using the Tilengine Python binding.

Here is a simple Python script that attempts to unpack a resource and create a spriteset from an asset:

# test.py

import os



os.add_dll_directory(os.getcwd())



from tilengine import *



engine = Engine.create(480, 270, 1, 1, 1)

engine.set_log_level(LogLevel.VERBOSE)

engine.open_resource_pack('assets.dat')



Spriteset.fromfile("test_asset")

I had to make some modifications to the binding to fix string encoding, as shown in this PR megamarc/PyTilengine#5

It results in the following output

PS C:\Users\flyho\workspace\resourcepacker-test> python .\test.py

Tilengine v2.9.1 64-bit built Apr  1 2021 08:10:58

Tilengine: Resource file not found

Traceback (most recent call last):

  File "C:\Users\flyho\workspace\resourcepacker-test\test.py", line 11, in <module>

    Spriteset.fromfile("test_asset")

  File "C:\Users\flyho\workspace\resourcepacker-test\tilengine.py", line 930, in fromfile

    _raise_exception()

  File "C:\Users\flyho\workspace\resourcepacker-test\tilengine.py", line 364, in _raise_exception

    raise TilengineException(error_string.decode())

tilengine.TilengineException: 'Resource file not found'



Here is my folder structure:

C:\USERS\FLYHO\WORKSPACE\RESOURCEPACKER-TEST

│   assets.dat

│   librespack.a

│   SDL2.dll

│   test.py

│   Tilengine.dll

│   tilengine.py

│

└───include

        ResPack.h



Is there anything I'm missing or doing incorrectly?

**Comment by megamarc** [comment]
Hi Daniel!
I've updated Tilengine to release 2.9.2 that restores compatibility with ResourcePacker. I haven't tested the python binding but it should work too. You can build from source of download updated binaries at itch.io

**Comment by danielgholmes** [comment]
Thanks!
